stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6-jdk-11
  script:
    - 'mvn package -s ci_settings.xml'
  tags:
    - docker

deploy:
  stage: deploy
  image: maven:3.6-jdk-11
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master
