server:
  port: ${SERVER_PORT:9000}


spring:
  mvc:
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:user_profiling_db}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:password}
    maxConnections: 10
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changeLog-master.xml
logging:
  level:
    root: INFO
  file:
    name: iddera-user-profiling-service.log
  logback:
    rollingpolicy:
      max-file-size: 50MB

resource:
  id: iddera-service
iddera:
  client:
    read-time-out: ${CLIENT_READ_TIMEOUT:40}
    connection-time-out: ${CLIENT_CONNECTION_TIMEOUT:40}
    write-time-out: ${CLIENT_WRITE_TIMEOUT:40}
    user-management-url: ${USER_MANAGEMENT_URL:https://iddera-user-management-api.herokuapp.com}
    client-id: ${CLIENT_ID:}
    client-secret: ${CLIENT_SECRET:}

swagger-auth-link: ${SWAGGER_AUTH_LINK:https://iddera-user-management-api.herokuapp.com}

meet:
  contact-name: ${MEET_CONTACT_NAME:IDDERA}
  contact-email: ${MEET_CONTACT_EMAIL:john@iddera.com}
zoom:
  api-key: ${ZOOM_API_KEY:H5YGY21jQvGlUt5si_hYxA}
  api-secret: ${ZOOM_API_SECRET:AQJHWQj8e3s2RPYlMO2peDME0quOwsjaL6N3}
  token-expiry-duration: ${ZOOM_TOKEN_EXPIRY_DURATION:60}
  base-url: ${ZOOM_BASE_URL:https://api.zoom.us/v2/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
